"-------------------------------------------
" basic
"

syntax on
set ai
set number
set encoding=utf-8
set visualbell
set noerrorbells

"-------------------------------------------
" NERDTree
"

let NERTreeCaseSensitiveSort=1
let NERDTreeQuitOnOpen=1

"-------------------------------------------
" whitespace
"


"-------------------------------------------
" searching
"

set hlsearch
set incsearch
set ignorecase
set smartcase

"-------------------------------------------
" scrolling
"

set scrolloff=5
set sidescrolloff=5
set sidescroll=1
